// <auto-generated />
using System;
using Ganjeh.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ganjeh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210106075831_state_city_tables_created")]
    partial class state_city_tables_created
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionStateId");

                    b.ToTable("RegionCity");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("[Title] IS NOT NULL");

                    b.ToTable("RegionCountries");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionCountryId");

                    b.ToTable("RegionState");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionCity", b =>
                {
                    b.HasOne("Ganjeh.Domain.Entities.RegionState", "RegionState")
                        .WithMany("RegionCities")
                        .HasForeignKey("RegionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionState");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionState", b =>
                {
                    b.HasOne("Ganjeh.Domain.Entities.RegionCountry", "RegionCountry")
                        .WithMany("RegionState")
                        .HasForeignKey("RegionCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionCountry");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionCountry", b =>
                {
                    b.Navigation("RegionState");
                });

            modelBuilder.Entity("Ganjeh.Domain.Entities.RegionState", b =>
                {
                    b.Navigation("RegionCities");
                });
#pragma warning restore 612, 618
        }
    }
}
